services:
  secret-santa:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes: 
      - database:/app/data
    restart: always


volumes:
  database:
