services:
  secret-santa:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    #    volumes: #Optional
    #      - ./secretSantaUltimate.sql:/app/secretSantaUltimate.sql
    restart: always
