services:
  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - nginx-redirect
    ports:
      - "80:80"
    restart: always

  back:
    container_name: back
    networks:
      - nginx-redirect
      - database
    build:
      context: back
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    restart: always

  database:
    container_name: database
    build:
      dockerfile_inline: |
        FROM postgres:16
        COPY db-init.sql /docker-entrypoint-initdb.d/seed.sql
    networks:
      - database
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "database"

networks:
  database:
    driver: bridge
  nginx-redirect:
    driver: bridge
