services:
  secret-santa:
    container_name: secret-santa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - santa-db:/app/data
    restart: always

volumes:
  santa-db:

